# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2a226df7-987a-4f62-b998-15ccff26e4ea'

  # Web app name
  webAppName: 'lamp1-ams-app'

  # Environment name
  environmentName: 'lamp1-ams-app'

  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Verify
  displayName: Verify
  jobs:
  - job: AppVerify
    pool: MVSLocalPool
    steps:
    - script: |
        copy .env.deploy .env
        composer install
      workingDirectory: $(rootFolder)
      displayName: 'Install Composer packages'

    - script: vendor\bin\phpcs --standard=phpcs.xml --extensions=php
      workingDirectory: $(rootFolder)
      displayName: 'Checking coding convention'

    - script: |
        type nul > database/database.sqlite
        php artisan test --env=testing --log-junit report/unit.xml --coverage-cobertura report/cobertura/coverage.xml
      workingDirectory: $(rootFolder)
      displayName: 'Perform unit testing'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/unit.xml'
        searchFolder: '$(rootFolder)/report'
        failTaskOnFailedTests: true

    - task: PublishCodeCoverageResults@1
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(rootFolder)/report/cobertura/coverage.xml'
        failIfCoverageEmpty: true

- stage: Build
  displayName: Build
  dependsOn: Verify
  condition: succeeded()
  variables:
    phpVersion: '7.3'
  jobs:
  - job: AppBuild
    pool: MVSLocalPool
    steps:
    - script: |
        copy .env.deploy .env
        composer install --no-interaction --optimize-autoloader --no-dev
      workingDirectory: $(rootFolder)
      displayName: 'Install Composer packages'

    - script: |
        call npm install
        call npm run prod
      workingDirectory: $(rootFolder)
      displayName: 'Build React UI using Webpack Mix'

    - script: |
        rmdir /Q /S node_modules
        del .env
      workingDirectory: $(rootFolder)
      displayName: 'Cleanup node_modules packages'

    - task: ArchiveFiles@2
      displayName: 'Packaging files'
      inputs:
        rootFolderOrFile: '$(rootFolder)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: WebAppDeployment
    pool: MVSLocalPool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Lamp1-RG-Connection'
              appType: 'webAppLinux'
              WebAppName: 'lamp1-ams-app'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
