export const homeConstants = {
  RESET_SORT_FILTER: 'RESET_SORT_FILTER_IN_HOME_LIST',
  SET_SORT_TYPE: 'SET_SORT_TYPE_IN_HOME_LIST',
  CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE_IN_HOME_LIST',
  GET_HOME_LIST: 'GET_HOME_LIST',
  ACCEPT_ASSIGNMENT_IN_HOME_LIST: 'ACCEPT_ASSIGNMENT_IN_HOME_LIST',
  DECLINED_ASSIGNMENT_IN_HOME_LIST: 'DECLINED_ASSIGNMENT_IN_HOME_LIST',
  CREATE_REQUEST_RETURN_IN_HOME_LIST: 'CREATE_REQUEST_RETURN_IN_HOME_LIST',
  USER_ACCEPT_ASSIGNMENT: 'USER_ACCEPT_ASSIGNMENT_IN_HOME_LIST',
  USER_DECLINE_ASSIGNMENT: 'USER_DECLINE_ASSIGNMENT_IN_HOME_LIST',
  USER_REQUEST_RETURN: 'USER_REQUEST_RETURN_IN_HOME_LIST',
}
