export const reportConstants = {
  RESET_SORT_FILTER: 'RESET_SORT_FILTER_IN_REPORT_LIST',
  SET_SORT_TYPE: 'SET_SORT_TYPE_IN_REPORT_LIST',
  CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE_IN_REPORT_LIST',
  GET_REPORT_LIST: 'GET_REPORT_LIST',
}
