export const requestConstants = {
  RESET_SORT_FILTER: 'RESET_SORT_FILTER_IN_REQUEST_LIST',
  SET_SORT_TYPE: 'SET_SORT_TYPE_IN_REQUEST_LIST',
  FILTER_BY_STATE: 'FILTER_BY_STATE_IN_REQUEST_LIST',
  FILTER_BY_RETURNED_DATE: 'FILTER_BY_RETURNED_DATE_IN_REQUEST_LIST',
  CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE_IN_REQUEST_LIST',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  GET_REQUEST_LIST: 'GET_REQUEST_LIST',
  UPDATE_DATA_FILTER: 'UPDATE_DATA_FILTER_REQUEST_LIST',
  ADMIN_COMPLETE_REQUEST: 'ADMIN_COMPLETE_REQUEST_IN_REQUEST_LIST',
  ADMIN_CANCEL_REQUEST: 'ADMIN_CANCEL_REQUEST_IN_REQUEST_LIST',
}
